export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const GOOGLE_AUTH = "GOOGLE_AUTH";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const CONTACT_HELP_MAIL_SUCCESS = "CONTACT_HELP_MAIL_SUCCESS";
export const CONTACT_HELP_MAIL_FAIL = "CONTACT_HELP_MAIL_FAIL";

export const SET_LAT_LNG = "SET_LAT_LNG";
export const SET_ADDRESS = "SET_ADDRESS";

export const LOCATION_CHECKIN = "LOCATION_CHECKIN";
export const LOCATION_CHECKIN_ERROR = "LOCATION_CHECKIN_ERROR";

export const FETCH_LOCATION_DETAILS = "FETCH_LOCATION_DETAILS";
export const FETCH_LOCATION_DETAILS_ERROR = "FETCH_LOCATION_DETAILS_ERROR";

export const GET_LOCATION_REVIEWS = "GET_LOCATION_REVIEWS";

export const GET_USER_VISITED_REVIEWS = "GET_USER_VISITED_REVIEWS";

export const EDIT_USER_PROFILE = "EDIT_USER_PROFILE";
export const EDIT_USER_PROFILE_SUCCESS = "EDIT_USER_PROFILE_SUCCESS";
export const EDIT_USER_PROFILE_FAILED = "EDIT_USER_PROFILE_FAILED";

export const GET_OTHER_USER_INFO = "GET_OTHER_USER_INFO";
export const GET_OTHER_USER_INFO_FAILED = "GET_OTHER_USER_INFO_FAILED";

export const SAVE_USER_PROFILE = "SAVE_USER_PROFILE";
export const ERROR_SAVE_USER_PROFILE = "ERROR_SAVE_USER_PROFILE";
export const GET_OTHER_USER_PROFILE = "GET_OTHER_USER_PROFILE";

export const REMOVE_USER_PROFILE = "REMOVE_USER_PROFILE";
export const REMOVE_USER_PROFILE_ERROR = "REMOVE_USER_PROFILE_ERROR";
